[mysql]
DB_HOST = "hopper.proxy.rlwy.net"
DB_USER = "root"
DB_PASSWORD = "NcFVFxnmCZReanbgvkWqUlVfKLRyZZiT"
DB_NAME = "proyecto_agricola"
DB_PORT = 16653

# Ejemplo (NO uses estos valores):
# DB_USER = "root"
# DB_PASSWORD = "mi_password_123"
# DB_HOST = "localhost"
# DB_PORT = 3306
# DB_NAME = "geoclima_db"
